spring.application.name=backend

spring.data.mongodb.uri=mongodb://localhost:27017/interview_platform

server.port=8080

onlinecompiler.api.url=https://api.onlinecompiler.io/api/run-code-sync/
onlinecompiler.api.key=9b2c85ce52b466b5ee9f16eb297be381

# Gemini API
gemini.api.key=${GEMINI_API_KEY:}
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent

# Allow larger logging during dev
logging.level.com.interviewplatform.backend.bot=INFO
logging.level.com.interviewplatform.backend.jwt=DEBUG