spring.application.name=backend

spring.config.import=optional:file:.env[.properties]

spring.data.mongodb.uri=mongodb://localhost:27017/interview_platform

server.port=8080

#Compiler Api
onlinecompiler.api.url=${ONLINE_COMPILER_API_URL:}
onlinecompiler.api.key=${ONLINE_COMPILER_API_KEY:}

# Gemini API
gemini.api.key=${GEMINI_API_KEY:}
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent

# Allow larger logging during dev
logging.level.com.interviewplatform.backend.bot=INFO
logging.level.com.interviewplatform.backend.jwt=DEBUG