spring.application.name=backend

spring.config.import=optional:file:.env[.properties]

spring.data.mongodb.uri=mongodb://localhost:27017/interview_platform

server.port=8080

onlinecompiler.api.url=${ONLINE_COMPILER_API_URL:}
onlinecompiler.api.key=${ONLINE_COMPILER_API_KEY:}